"""add group_booking_requests table

Revision ID: 1a2b3c4d5e6f
Revises: fcb746dd4ab7
Create Date: 2026-09-22 10:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = 'fcb746dd4ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_booking_requests',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_ref', sa.String(length=50), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=False),
    sa.Column('organization_type', sa.String(length=30), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=150), nullable=False),
    sa.Column('attraction_slot_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('indian_travelers_count', sa.Integer(), nullable=True),
    sa.Column('foreign_travelers_count', sa.Integer(), nullable=True),
    sa.Column('total_headcount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('roster_json', sa.Text(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attraction_slot_id'], ['attraction_slots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_booking_requests_request_ref'), 'group_booking_requests', ['request_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_booking_requests_request_ref'), table_name='group_booking_requests')
    op.drop_table('group_booking_requests')
    # ### end Alembic commands ###
